# Generated by Django 4.2.11 on 2024-04-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0004_category_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='./product_images/'),
        ),
    ]
