# Generated by Django 4.2.11 on 2024-04-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0007_user_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
