# Generated by Django 4.2.11 on 2024-05-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_page', '0012_alter_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationsAndDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='presentations_and_docs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='presentations_and_docs_images/')),
            ],
        ),
    ]
